### ISSUE TITLE
Use GameState structure 

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/OpenLoco#1132]
#1129 introduced the gamestate structure and used it for all manager code. There are a lot of places where it should also be used for other code such as the objective options:
```cpp
    static loco_global<uint8_t, 0x00526230> objectiveType;
    static loco_global<uint8_t, 0x00526231> objectiveFlags;
    static loco_global<uint32_t, 0x00526232> objectiveCompanyValue;
    static loco_global<uint32_t, 0x00526236> objectiveMonthlyVehicleProfit;
    static loco_global<uint8_t, 0x0052623A> objectivePerformanceIndex;
    static loco_global<uint8_t, 0x0052623B> objectiveDeliveredCargoType;
    static loco_global<uint32_t, 0x0052623C> objectiveDeliveredCargoAmount;
    static loco_global<uint8_t, 0x00526240> objectiveTimeLimitYears;
    static loco_global<uint16_t, 0x00526241> objectiveTimeLimitUntilYear;
```
All of the above fields are in the gamestate structure and should be accessed via getGameState(). I'd prefer we don't include gamestate.h in a lot of locations so this may require some careful thinking. The above objective options should probably be grouped into a single structure.

**Comment by LeftofZen** [comment]
> I'd prefer we don't include gamestate.h in a lot of locations

What are the reasons for this approach?

**Comment by duncanspumpkin** [comment]
Game state.h has to include pretty much every header that includes some sort of game logic. Therefore it ends up being a heavy header that would force lots of file recompiles if it has any changes. By limiting the header from only being included in manager cpp files it means that only manager files need to be recompiled lots.

**Comment by memellis** [comment]
Has this issue now been addressed by [#1765](https://github.com/OpenLoco/OpenLoco/pull/1765) ?

**Comment by AaronVanGeffen** [comment]
@memellis No, that PR does not defer to the GameState structure. We need a bunch more globals to be working with the GameState structure instead in order for this issue to be closed.

**Comment by memellis** [comment]
Hi, I'd like to make a contribution to this as a good first issue, but just need a hint as to which bunch of globals need to be working with the GameState structure instead.

**Comment by duncanspumpkin** [comment]
any global variable that is in the range from 0x00525E18 to 0x00987C5C. There are quite a lot still.

**Comment by AaronVanGeffen** [comment]
Ideally, we'd have also only have _one_ route to access particular members of the game state. This makes access to particular members more self-contained.

For example, a routine that deals with town-related logic shouldn't access the town directly from the `GameState`. Instead, it goes to the `TownManager` to access particular town. That way, only `TownManager` needs to include the `GameState` under the hood.

**Comment by memellis** [comment]
Globals 0x00525E18 to 0x00987C5C:
- RemoveTree.cpp:  static loco_global<Core::Prng, 0x00525E20> _prng;
- VehiclePickup.cpp:  static loco_global<Core::Prng, 0x00525E20> _prng;
- GameState.cpp:  loco_global<GameState, 0x00525E18> _gameState;
- RoadElement.cpp: static loco_global<uint32_t, 0x00525FBC> _525FBC;
- TileManager.cpp: static loco_global<World::Pos2, 0x00525F6E> _startUpdateLocation;
- Track.cpp: static loco_global<uint32_t, 0x00525FC0> _525FC0;
- WaveManager.cpp: static loco_global<Core::Prng, 0x00525E20> _prng; // not the gPrng
- OpenLoco.cpp static loco_global<int16_t, 0x00525F62> _525F62;
- S5.cpp: static loco_global<GameState, 0x00525E18> _gameState;
-  Tile.cpp: static loco_global<uint16_t, 0x00525F62> _525F62;
- CreateVehicle:  static loco_global<uint32_t, 0x00525FB8> _orderTableLength;          // total used length of _987C5C
-                         static loco_global<uint8_t[Limits::kMaxOrders], 0x00987C5C> _987C5C; // ?orders? ?routing related?
- Orders.cpp: static loco_global<Order[Limits::kMaxOrders], 0x00987C5C> _orderTable;
- Vehicle.cpp: static loco_global<uint32_t, 0x00525FBC> _525FBC;     // RoadObjectId bits
- VehicleBody.cpp:  static loco_global<bool, 0x00525FAE> _trafficHandedness;           // boolean true for right false for left
-  Construction.h: static loco_global<uint8_t[8], 0x0525F72> _scenarioSignals;
                             static loco_global<uint8_t[8], 0x0525F7A> _scenarioBridges;
                             static loco_global<uint8_t[8], 0x0525F82> _scenarioTrainStations;
                             static loco_global<uint8_t[8], 0x0525F8A> _scenarioTrackMods;
                             static loco_global<uint8_t[8], 0x0525F9A> _scenarioRoadStations;
                             static loco_global<uint8_t[8], 0x0525FA2> _scenarioRoadMods;
                            static loco_global<bool, 0x00525FAE> _trafficHandedness; // boolean true for right false for left
- LandscapeGeneration.cpp: static loco_global<uint16_t, 0x00525FB2> _seaLevel;
- MapWindow.cpp: static loco_global<WindowFlags, 0x0526284> _lastMapWindowFlags;
                               static loco_global<Ui::Size, 0x00526288> _lastMapWindowSize;
                              static loco_global<uint16_t, 0x0052628C> _lastMapWindowVar88A;
                              static loco_global<uint16_t, 0x0052628E> _lastMapWindowVar88C;
- MessageWindow.cpp: static loco_global<uint16_t, 0x005271CE> _messageCount;
- News.h: static loco_global<uint16_t, 0x005271CE> _messageCount;
- Vehicle.cpp: static loco_global<uint8_t, 0x00525FB0> _pickupDirection; // direction that the ghost points
- CompanyManager.cpp: static loco_global<uint8_t, 0x00525FCB> _byte_525FCB;

Are these the globals (31 of them) that need to be working with the GameState structure instead?
- With only one route to access particular members of the game state?

**Comment by duncanspumpkin** [comment]
Yup.

**Comment by memellis** [comment]
For this issue #1132 these this is the list of globals:

- [x] RemoveTree.cpp: static loco_global<Core::Prng, 0x00525E20> _prng; removed by commit [3f3aa27accd2a65dd29a3f9e6b0f80a938660e72](https://github.com/openloco/openloco/commit/3f3aa27accd2a65dd29a3f9e6b0f80a938660e72) 
- [x] VehiclePickup.cpp: static loco_global<Core::Prng, 0x00525E20> _prng; removed by commit [3f3aa27accd2a65dd29a3f9e6b0f80a938660e72](https://github.com/openloco/openloco/commit/3f3aa27accd2a65dd29a3f9e6b0f80a938660e72)
- [ ] GameState.cpp: loco_global<GameState, 0x00525E18> _gameState; NOT DONE
- [x] RoadElement.cpp: static loco_global<uint32_t, 0x00525FBC> _525FBC removed by commit [86c12df41731dbf18e0018392e6c222f30138c21](https://github.com/openloco/openloco/commit/86c12df41731dbf18e0018392e6c222f30138c21)
- [x] TileManager.cpp: static loco_global<World::Pos2, 0x00525F6E> _startUpdateLocation; removed by commit [adf9a75c9eda46314b58042dc8a7e30732296d6c](https://github.com/openloco/openloco/commit/)
- [x] Track.cpp: static loco_global<uint32_t, 0x00525FC0> _525FC0  removed by commit [9213cac15d42afa733bf8a19efba44d7fb874fb6](https://github.com/openloco/openloco/commit/9213cac15d42afa733bf8a19efba44d7fb874fb6)
- [x] WaveManager.cpp: static loco_global<Core::Prng, 0x00525E20> _prng; // not the gPrng removed by commit [3f3aa27accd2a65dd29a3f9e6b0f80a938660e72](https://github.com/openloco/openloco/commit/3f3aa27accd2a65dd29a3f9e6b0f80a938660e72)
- [x] OpenLoco.cpp static loco_global<int16_t, 0x00525F62> _525F62; removed by commit [0e4d3c9fee0e7759c5e196ebd99fc86c3596f729](https://github.com/openloco/openloco/commit/0e4d3c9fee0e7759c5e196ebd99fc86c3596f729)
- [] S5.cpp: static loco_global<GameState, 0x00525E18> _gameState; NOT DONE
- [x] Title.cpp: static loco_global<uint16_t, 0x00525F62> _525F62; removed by commit [0e4d3c9fee0e7759c5e196ebd99fc86c3596f729](https://github.com/openloco/openloco/commit/0e4d3c9fee0e7759c5e196ebd99fc86c3596f729)
- [x] CreateVehicle: static loco_global<uint32_t, 0x00525FB8> _orderTableLength; // total used length of _987C5C removed by commit  [06a6d6c63842628271db3ff5e2ab741b3747f603](https://github.com/openloco/openloco/commit06a6d6c63842628271db3ff5e2ab741b3747f603/)
- [x] Orders.cpp: static loco_global<Order[Limits::kMaxOrders], 0x00987C5C> _orderTable; removed by commit [8e782f3aa32d6cd83d19f6e03bd0cb26ea6c1859](https://github.com/openloco/openloco/o8e782f3aa32d6cd83d19f6e03bd0cb26ea6c1859penloco/commit/)
- [x] Vehicle.cpp: static loco_global<uint32_t, 0x00525FBC> _525FBC; // RoadObjectId bits removed by commit [86c12df41731dbf18e0018392e6c222f30138c21](https://github.com/openloco/openloco/commit/86c12df41731dbf18e0018392e6c222f30138c21)
- [x] VehicleBody.cpp: static loco_global<bool, 0x00525FAE> _trafficHandedness; // boolean true for right false for left removed by commit [0b9634c323c0e7f7ec0d5fb3b211ab55fbc99fe3](https://github.com/openloco/openloco/commit/0b9634c323c0e7f7ec0d5fb3b211ab55fbc99fe3)
- [x] Construction.h: static loco_global<uint8_t[8], 0x0525F72> _scenarioSignals;
- [x]                 static loco_global<uint8_t[8], 0x0525F7A> _scenarioBridges;
- [x]                 static loco_global<uint8_t[8], 0x0525F82> _scenarioTrainStations;
- [x]                 static loco_global<uint8_t[8], 0x0525F8A> _scenarioTrackMods;
- [x]                 static loco_global<uint8_t[8], 0x0525F9A> _scenarioRoadStations;
- [x]                 static loco_global<uint8_t[8], 0x0525FA2> _scenarioRoadMods; removed by commit [35daeff471f66f475535eaa511af88a4350312ce](https://openloco/openloco/commit/35daeff471f66f475535eaa511af88a4350312ce)
- [x]                 static loco_global<bool, 0x00525FAE> _trafficHandedness; removed by commit [89c513f762515c3636abb9345edf3b5607064204](https://github.com/openloco/openloco/commit/89c513f762515c3636abb9345edf3b5607064204)
- [x] LandscapeGeneration.cpp: static loco_global<uint16_t, 0x00525FB2> _seaLevel; removed by commit [b700424b77cf2d868bb95de7aae77047f3584beb](https://github.com/openloco/openloco/commit/b700424b77cf2d868bb95de7aae77047f3584beb)
- [x] MapWindow.cpp: static loco_global<WindowFlags, 0x0526284> _lastMapWindowFlags; removed by commit [7b22221014c4b6c0570766501c279943b719fa98](https://github.com/openloco/openloco/commit/7b22221014c4b6c0570766501c279943b719fa98)
- [x]                static loco_global<Ui::Size, 0x00526288> _lastMapWindowSize;
- [x]                static loco_global<uint16_t, 0x0052628C> _lastMapWindowVar88A;
- [x]                static loco_global<uint16_t, 0x0052628E> _lastMapWindowVar88C;
- [x] MessageWindow.cpp: static loco_global<uint16_t, 0x005271CE> _messageCount; removed by commit [3b8de9275d50161aae11cac6f4de133f489a5131](https://openloco/openloco/commit/3b8de9275d50161aae11cac6f4de133f489a5131)
- [x] News.h: static loco_global<uint16_t, 0x005271CE> _messageCount; removed by commit 3b8de9275d50161aae11cac6f4de133f489a5131[](https://openloco/openloco/commit/3b8de9275d50161aae11cac6f4de133f489a5131)
- [x] Vehicle.cpp: static loco_global<uint8_t, 0x00525FB0> _pickupDirection; // direction that the ghost points removed by commit [86c12df41731dbf18e0018392e6c222f30138c21](https://github.com/openloco/openloco/commit/86c12df41731dbf18e0018392e6c222f30138c21) 
- [x] CompanyManager.cpp: static loco_global<uint8_t, 0x00525FCB> _byte_525FCB; removed by commit [79680b7e00856052ef24f9242bf9f6876589fd4b](https://github.com/openloco/openloco/commit/79680b7e00856052ef24f9242bf9f6876589fd4b)	

With two not done:
- [ ] GameState.cpp: loco_global<GameState, 0x00525E18> _gameState; NOT DONE
- [ ] S5.cpp: static loco_global<GameState, 0x00525E18> _gameState; NOT DONE
Which I assume is because this is used to make the gamestate structure exist in the same memory space as the    OpenLoco original binary executable.

**Comment by duncanspumpkin** [comment]
Oh great that means we have done them all. Yes the two gamestate globals are needed (although it should really be just the one I've been a bit cheeky and done some undefined behaviour around there)

**Comment by memellis** [comment]
Great! I think that means this issue can be closed?
I'll start looking at something else to work on.
