### ISSUE TITLE
Feature: Vehicles should display their maximum capacity in their cargo menu

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1271]
**Suggested Feature**
Currently, vehicles display the current amount of cargo they are carrying, which is great, but if you want to know their maximum capacity, you need to do a bit of math. It would be convenient if there was a statistic in a vehicle's menu (probably in the cargo tab) that says what the maximum amount of each cargo that vehicle can carry.

Hypothetical example: A train has 3 passenger carriages (each can hold 20) and 2 mail wagons (each can hold 15). Therefore:

Total: 42 passengers, 12 bags of mail (This is the current cargo count of the vehicle. This is an existant feature)
Maximum capacity: 60 passengers, 30 bags of mail (This is the maximum capacity of the vehicle. This is what I am suggesting)

**Additional context**
ideally, it would be listed under the total capacity (so it can easily be read without making the window really big). It might also be helpful to relabel "Total Capacity" as "Current Cargo", Like so:

Current Cargo: 42 passengers, 12 bags of mail
Maximum Capacity: 60 passengers, 30 bags of mail

**Comment by LeftofZen** [comment]
Some info

- The string `Total: <amount> of <cargo>` is drawn in `OpenLoco::Ui::Windows::Vehicle::Cargo::draw()`
- The string is generated in `OpenLoco::Vehicles::VehicleHead::generateCargoTotalString()`
- The way the total is calculated for each cargo is, an array is used as a LUT with the cargo type used as index/lookup, and the we iterate over each car in the train, look at it's `VehicleCargo` member struct, grab `qty` from it, and sum these up.
- `VehicleCargo` struct has a property `maxQty`
- After the cargo is summed into this array, the string is generated in the `buffer` that was passed in.

Therefore the obvious implementation is to copy-paste the function and simply change this
```
 if (front->secondaryCargo.type != 0xFF)
{
    cargoTotals[front->secondaryCargo.type] += front->secondaryCargo.qty;
}
if (body->primaryCargo.type != 0xFF)
{
    cargoTotals[body->primaryCargo.type] += body->primaryCargo.qty;
}
```

into
```
 if (front->secondaryCargo.type != 0xFF)
{
    cargoTotals[front->secondaryCargo.type] += front->secondaryCargo.maxQty;
}
if (body->primaryCargo.type != 0xFF)
{
    cargoTotals[body->primaryCargo.type] += body->primaryCargo.maxQty;
}
```


I did a quick hack by just replacing the existing code with the `maxQty` version, and it works; here is a train with 8*20 ton carriages:
![image](https://user-images.githubusercontent.com/7483209/150730168-e1d2da82-ffca-4d5e-882f-bb2dfeaee42d.png)

So all that is necessary to do here is add some extra space into the train cargo tab to print both lines of text instead of just 1.

**Comment by LeftofZen** [comment]
I guess I'll just implement the whole thing haha
![image](https://user-images.githubusercontent.com/7483209/150731459-719327ce-2304-4152-a520-5d1adf14d987.png)

**Comment by LeftofZen** [comment]
Added in #1306
