### ISSUE TITLE
Changing cargo between vehicles bugged

### ISSUE THREAD

**Issue by YetiWiz** [OpenLoco/OpenLoco#130]
If you unload cargo to a station and have another vehicle pick it up to finish the delivery, the days needed for the whole trip will add up every time. Say you want to have a ship deliver oil to the shore and then have a train take it over to deliver it to the refinery. Because of this bug, the game will always think that it took 255 days and you would get minimum profit. This bug is from the original game.
An example: The right train is forced to unload coal to the central station, the left than takes it to the Steel Mill. There is no way this took 255 days.
![bug](https://user-images.githubusercontent.com/36667284/36428606-a5ce9604-1650-11e8-9fd5-1a893f4ae291.jpg)

**Comment by jgottula** [comment]
Yeah, I've actually come across this original game bug as well during regular gameplay. Dropping off cargo temporarily at a "transfer" station and then picking it up from that station and completing its delivery on a second route would seem to result in the delivery supposedly taking 255 days (and giving horrendously low income based on that phony duration).

It also seemed to me that if there was already a bunch of a particular type of cargo waiting at the transfer station for a long time, and then a vehicle dropped off some additional, relatively-fresh cargo of the same type, then that fresh cargo would get "infected" by the oldness of the existing cargo that had already been waiting at the transfer station for a long time.

Basically what I mean by the paragraph above, is that I got the (unconfirmed/untested) impression that once some cargo had been dropped off at a transfer station, then the "age" of all cargo of that type at the station would continually rise as long as there was continuously a nonzero amount of it at the station. Even if there was just 1 unit of old cargo, and a train dumped 300 tons of very fresh cargo of that type, the station would then contain 301 units of cargo which would all be considered to be as old as the oldest cargo at the station (the 1 unit in this case). Which would inevitably lead to the age of all the cargo at the station eventually reaching 255 days, unless the station was ever *completely emptied* of all of that type of cargo.

Again, that hypothesis is unconfirmed, and it could just be the case that there's a very simple bug/oversight where cargo being transferred in this manner is always set to the max possible age of 255 days for some reason. But it seems logical to me that stations most likely keep track of the cargo contained within them (at least dropped-off cargo, not produced-by-things-in-the-station's-catchment-area cargo; they may be kept track of separately) by merely tracking the total quantity for each cargo type, along with an age value that implicitly applies to all of the cargo of that type. And then whenever cargo of a particular type is dropped off at the station (force-unloaded for transfer, not unloaded for immediate delivery to a consumer in the station's catchment area), if there is already a nonzero quantity of that cargo type at the station, then the quantity is merely increased by the amount dropped off, and the age either retains its existing value, or it's assigned the `max` of the existing value and the age of the dropped-off cargo.

So fundamentally the problem may be that stations have an overly simplistic "just a single quantity and age value for each cargo type" model for tracking cargo they have, instead of keeping track of potentially multiple different sets of same-typed cargo that have different ages from each other.

I may do some tests to see if I can validate or falsify this notion to some degree...

**Comment by auge8472** [comment]
> So fundamentally the problem here is very likely that stations have an overly simplistic "just a single quantity and age value for each cargo type" model for tracking the cargo they have, instead of keeping track of potentially multiple different sets of same-typed cargo that have different ages from each other. Ideally, stations would do the latter (store multiple quantity+age pairs for each differently-aged set of cargo of that type), and ideally stations would also make vehicles which are picking up the cargo prioritize loading the oldest stuff first, so that older cargo units don't just sit there at the station collecting dust.

Maybe it's a solution to middle the age of two or more supplies of the same cargo. That would be possible without changing the save format.

supply | amount | age
--------|----------|------
1 | 10 | 20
2 | 10 | 5
**avg.** | \- | **12.5**

**Comment by IntelOrca** [comment]
> So fundamentally the problem here is very likely that stations have an overly simplistic "just a single quantity and age value for each cargo type" model for tracking the cargo they have...

Correct, you can already look at the rating calculation code to give you an idea on that.
