### ISSUE TITLE
Game Launcher?

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#1533]
I think it would make plenty of sense for a game launcher to be created. OpenRCT2 and OpenTTD both have one, and yet this game does not, which I do not understand. The launchers for both also have settings to configure multiplayer and other details, such as window snapping (windows "connect" when dragged close to each other) and a few other in-game settings.

**Additional context**
I have a feeling a feature like this would be given the "epic" tag, all things considered.

**Comment by LeftofZen** [comment]
> which I do not understand

There are other more important things to do like continuing the decompilation/reverse engineering work, and there are only a few devs working on OpenLoco in a very part-time/casual sense.

A launcher will happen one day, but at the moment it isn't close to being a priority as far as I'm aware.

**Comment by duncanspumpkin** [comment]
We never made one for openrct2 we left it to the community to make one. Feel free to make one.

**Comment by IntelOrca** [comment]
@Derpercoaster I am not aware of any OpenTTD launcher, can you post a link to it?

**Comment by Derpercoaster** [comment]
> @Derpercoaster I am not aware of any OpenTTD launcher, can you post a link to it?

Made a mistake on that one, turns out there isn't a launcher, for some reason I thought there was one.

**Comment by janisozaur** [comment]
That's a terrible idea. There are enough problems with the current launcher you mentioned for OpenRCT2:
1. It tries to provide configuration options, but is very much out of sync with what options are already avaialble
2. there's no launcher for the launcher, so users are stuck with whatever version they downloaded initially
3. it _tries_ to download incorrect openrct2 versions (e.g. x86 version on amd64 host)
4. it fails to download current versions
5. if it fails to download, it prevents user from launching local copy
6. it fails to update present copy if it ever downloads a new one

**Comment by IntelOrca** [comment]
I am working on a simple Windows launcher, here is a preview:
![image](https://user-images.githubusercontent.com/1482259/173255702-d761fbcb-7d1e-42b0-9fa3-ec185ca1378b.png)

All of @janisozaur 's points are not an issue with this launcher, with the exception of 2), although it could say there is an update for the launcher - or auto update. The benefit to me and others is that it will be line the Minecraft launcher and allow you to pick any historical version which is great for quickly bisecting or rolling back a bad build.

It currently can only obtain release builds as the octokit library I am using does not support GitHub Actions, which means I can't query or pull download links from the CI runs. It also requires you to be logged in, so not sure how I will get past that. OpenRCT2 archives its commit builds on a separate repo as releases, so that might be an option for OpenLoco.

**Comment by IntelOrca** [comment]
Okay, first release is available:
https://github.com/IntelOrca/OpenLauncher/releases

Please report any issues or features suggestions there.
It is currently limited to Windows. If it is to support other platforms, then I will need to switch to a different UI framework like Avalonia.
