### ISSUE TITLE
Crash in Order Flag viewport draw

### ISSUE THREAD

**Issue by duncanspumpkin** [OpenLoco/OpenLoco#2111]
**Version information:**
 - Platform: Windows 10
 - Version: 23.08 ? probably .1 as well as it doesn't seem related to the .1 fix

**Describe the bug**
Crash at https://github.com/OpenLoco/OpenLoco/blob/f538076483f21e7cc27eea21cc847b9fd7b5d34d/src/OpenLoco/src/Viewport.cpp#L218 with a nullptr for the order. Unsure how this state was reached but it would be easy to prevent it from causing a crash.

**Comment by asbaktemporary** [comment]
![image](https://github.com/OpenLoco/OpenLoco/assets/98380952/3ff063e6-1b5e-41ae-ad54-c05ee1a88f15)
giving flag on 23.08.1 still exist

**Comment by Mohsin-Ul-Islam** [comment]
Hi, can I work on this issue?

**Comment by LeftofZen** [comment]
> Hi, can I work on this issue?

Yes you can work on any issue; you don't need to ask for permission to submit PRs to open-source projects.

**Comment by Mohsin-Ul-Islam** [comment]
I would appreciate any guidance here. Do we need to guard against the `nullptr` only? If yes, do we need to add this change to all places where the return type can be a `nullptr`.

Or is there a better solution to handling such `nullptr `errors?

**Comment by LeftofZen** [comment]
Generally in programming it's better to fix the data at the source rather than adding error handling everywhere. So I personally would prefer to first figure out exactly why there is a nullptr in `orderRing`. If it is valid to have a nullptr in it, then yep all we need is to check for the nullptr like your PR. If however we do not expect nullptr to be there, we should instead find out why/how it's nullptr and fix it at the source instead.

**Comment by Mohsin-Ul-Islam** [comment]
Hi, cannot seem to replicate the bug on my local machine. I also tried to find the issue source but couldn't.

I would appreciate any guidance. Thanks

**Comment by LeftofZen** [comment]
If there are no repro steps then it'll be hard to diagnose. So either a) try to find some repro steps, or maybe someone has a save file with the issue already occurring, or b) leave this issue for now and try another one
