### ISSUE TITLE
Crash when pressing SHIFT to build below ground

### ISSUE THREAD

**Issue by SteveEmfore** [OpenLoco/OpenLoco#2612]
**Version information:**
 - Platform: [e.g. Windows 11]
 - Version: [e.g. 24.08]
 - Build/commit: [e.g. f08479f]

**Describe the bug**
Crash when pressing SHIFT to build below ground. I was building a tram line and used SHIFT to build below ground.

**Expected behaviour**

**Screenshots**
![image](https://github.com/user-attachments/assets/134dc258-ad29-4fd5-8ff2-411aa6f2fb8a)
[autosave_2024-08-30_14-59-44.zip](https://github.com/user-attachments/files/16818146/autosave_2024-08-30_14-59-44.zip)

**Comment by duncanspumpkin** [comment]
Are you able to upload the dmp file? What tool were you using underground? Track? Road?

**Comment by SteveEmfore** [comment]
Apologies, here's the file:

I was using Tram lines without road.

**Comment by duncanspumpkin** [comment]
Somethings gone wrong with that upload the link is to nothing could you try again?

**Comment by SteveEmfore** [comment]
[2b914b0d-96ab-4ab4-b6d7-2fc97d15ebc0(OpenLoco, v24.08 (40e9b7bf on master)).dmp](https://github.com/user-attachments/files/16818978/2b914b0d-96ab-4ab4-b6d7-2fc97d15ebc0.OpenLoco.v24.08.40e9b7bf.on.master.dmp)

**Comment by duncanspumpkin** [comment]
its crashing in a function we haven't implemented road placement. Trams are a type of road. Issue is that the roadmod (overhead wires) are referencing an object that doesn't exist. This is happening because the mods that are selected is 0xFF instead of 0x1. This is happening because the z height is negative and sign extending into the mods. This is happening because the initial construction height is 0. This is happening because something is slightly different with underground view with the surface paint function.

So...
Lots of issues, lots of places where things have gone wrong. Z should never be negative so thats an easy one to protect against. Easy enough to stop the z sign extending into the mods. What I'm not sure about is what is wrong with the surface paint code.

**Comment by duncanspumpkin** [comment]
ahh its not surface paint with the issue its https://github.com/OpenLoco/OpenLoco/pull/2550
