### ISSUE TITLE
Game crashes crashes on startup (Windows)

### ISSUE THREAD

**Issue by PhiliThunder** [OpenLoco/OpenLoco#299]
OS:  Windows 10
Version:  v19.03
Commit/Build:  016d24d

The game crashes and quits with no message when i try to start it. It happens right after windows scales its resolution to launch the game. I have set the game to go full-screen (1920x1080 the option menu said). It worked fine yesterday, but trying to launch it today changing nothing had this happen.

Steps to reproduce:
1. Enable full-screen and make sure the option menu says 1920x1080 (maybe...)
2. Re-launch the game

Is the issue reproducible in Locomotion (vanilla)?
No

Screenshots / Video:
Here is how it looks: https://www.youtube.com/watch?v=4rYhw0Uzti4 (Sorry bad quality from phone, only way to record it fully)

**Comment by PhiliThunder** [comment]
I am not sure where you save user settings specific to OpenLoco, but i want to add: Reinstalling OpenLoco did not fix my issue.

**Comment by Zcooger** [comment]
Check %appdata%\OpenLoco directory. There are 2 files with settings.

**Comment by PhiliThunder** [comment]
OK, i deleted those and tried launching. It works so i can confirm the problem had something to do with those settings.

The openloco.yml file said this before resetting: 
display:
  mode: window
  window_resolution:
    width: 0
    height: 0
  fullscreen_resolution:
    width: 0
    height: 0
audio:
  {}
loco_install_path: C:\Program Files (x86)\Atari\Locomotion
language: en-GB
breakdowns_disabled: false
scale_factor: 1
zoom_to_cursor: true

**Comment by PhiliThunder** [comment]
When choosing fullscreen and not choosing resolution, it defaults to 65535x65535, but then opens like this: https://www.youtube.com/watch?v=_00EkHCZRFw

**Comment by IntelOrca** [comment]
@PhiliThunder Does the game work properly when choosing window mode or `Fullscreen (borderless window)`?

**Comment by PhiliThunder** [comment]
Yes, also when choosing fullscreen and not closing the game. Or choosing fullscreen+1080p and re-launching in a short time after. As it still works now.
Maybe some other settings made it happen, but i can't see which or how.

**Comment by Snowfckingwhite** [comment]
For some reason I can't figure out how to install this game... I unpacked the .zip file, I launched openloco.exe, selected the path where Locomotion is installed and then... nothing. I tried to launch it again and... nothing. All that happens is that a small window and a cmd is popping up for like a second. Because of that, it was hard to read what the cmd said before the program just closes without any warning but I figured out that it simply said "File not found: "C:\\Users\\User\\AppData\\Roaming\\OpenLoco\\game.cfg"" At first I thought, that I missed something or that I would have to reinstall but the file just will not appear in the said folder no matter how often I try to install it :\  The only files showing up in this folder are openloco.yml, plugin.dat and scores.dat. I really need help with this it just confuses me right now... Should I consider installing another version (I've only tried v20.03 by now) or should I try to redownload the file in case that something could've gone wrong with the download or is this just a common thing and I'm just to dumb to check it? All I know is that the program needs files and I don't have them for some reason.

**Comment by AaronVanGeffen** [comment]
@Snowfckingwhite Thanks for the report. It's very unfortunate that this kind of bug made it into the release. Most of our devs are not on Windows, which is likely the reason this was overlooked.

Does the issue also present itself with a recent development build? I ask because #430 (#434) fixed a bug that might be related. You could try the artefact for [this job](https://github.com/OpenLoco/OpenLoco/suites/683449394/artifacts/6338079), for example.

Regardless, I intend to get this sorted for the next release.

**Comment by Snowfckingwhite** [comment]
Thanks for the reply. I've tried the file you attached to the link and even though the cmd still says that the game.cfg file is missing (only on first startup), the game starts and is fully playable.
![20200517_223623](https://user-images.githubusercontent.com/65474043/82159601-ad180800-988f-11ea-92da-1267806eeabc.jpg)

**Comment by AaronVanGeffen** [comment]
Thanks, that’s great news. Very glad to hear this. 

The line in the console is a warning-level log message. Perhaps we should amend it to reflect that.
