### ISSUE TITLE
Tutorials crash the game out

### ISSUE THREAD

**Issue by hypercube33** [OpenLoco/OpenLoco#397]
**OS:**  Windows 10 1909
**Version:**  Current - 19.03
**Commit/Build:**  (2019-03-01)

Launching the game and trying to load tutorial 1 crashes the game back to windows.

**Steps to reproduce:**
1. Open Game
2. Point to steam directory (in my case, its on my D:\Games\Steam...)
3. Open the game
4. In my case, I opened a new map, whatever default or is selected to make sure it loads
5. I then load the game any other time and try to do a tutorial and the game crashes.

**Is the issue reproducible in Locomotion (vanilla)?**
Not that I can tell. The tutorial sucks but thats a different subject :)

**Screenshots / Video:**

**Save game:**

**Comment by IntelOrca** [comment]
Tutorials will likely need disabling as we did for OpenRCT2. They rely heavily on a fixed UI at a fixed resolution.

**Comment by seifer7** [comment]
@IntelOrca I don't think disabling them is the way to go. They can be helpful to new players, not everyone has played the original game or TTD.

Maybe a popup Window before the tutorial starts mentioning that "due to the tutorials being from the original 2004 game, they must be played in 800x600 screen resolution. Click continue to change your resolution and start the tutorial"

I just checked the original game and this is actually exactly what it does, just without a warning.

Question: Do we have any tools for snooping the tutorial files? I'd love to take a look at them and see if it were possible to dynamically adjust the mouse movements based on the selected resolution. 😁

**Comment by AaronVanGeffen** [comment]
They can be helpful, yes, but the current set of tutorials are merely recordings of cursor positions and tutorial string ids to show. Inherently, these do not scale to anything other than the resolutions they were designed for.

We do not necessarily have to switch to a fullscreen resolution — as long as the window (canvas) size matches, it should be fine. You'd have to resize the window to match the closest recording to do this, though. If no close match is available, it should fail gracefully. Changing mode to fullscreen in different resolution is not an option regardless, imo.

I am not sure this is worth the hassle, to be honest. But feel free to pick it up.

**Comment by IntelOrca** [comment]
And as soon as we alter the UI, positions of buttons etc. will change. Most of the OpenRCT2 tutorials would fail just because we added the fast forward button to the toolbar.

**Comment by seifer7** [comment]
You're right. After i commented I thought about the fact that any UI changes would break the tutorials regardless of the screen resolution issue.
I'm going to explore the ability to create a new tutorial format that uses widget ids instead of x/y coords for mouse movements. 
Would mean re-recording the tutorials, but could open up the ability to make additional ones.
