### ISSUE TITLE
Game crashes with clean install of v20.03

### ISSUE THREAD

**Issue by RaymanXY** [OpenLoco/OpenLoco#415]
**OS:** Windows 10
**Version:**  20.03
**Commit/Build:**  

I know this project is in early stage, but people looking for an easy way to try out this game are usually downloading the lastest zip-file and try to start the game. And this doesn't work as desired. 

Unfortunately the game crashes at first startup after selecting the locomotion install directory. This happens only with the newest release v20.03, downloaded at https://github.com/OpenLoco/OpenLoco/releases/download/v20.03/openloco-v20.03-win32.zip

It crashes because the game can not load the "game.cfg" file. If you first start the v19.03 release, the config files are being created correctly and after updating to v20.03, the game is still loading.

For an easy setup experience for new players, I recommend to fix this release.

**Steps to reproduce:**
1. Delete your setting folder "OpenLoco" in %AppData%
2. Unzip v20.03 release
3. Start openloco.exe
4. Select install directory of Locomotion
5. Game crashes because it can not load game.cfg (because it does not yet exist)

**Is the issue reproducible in Locomotion (vanilla)?** No

**Screenshots / Video:** n/a

**Save game:** n/a

**Comment by andrejp88** [comment]
I had the same issue. I tried launching 19.03 first, then 20.03. It still fails to launch, but this time without any error messages. It just prints `OpenLoco, v20.03 (2e212af on master)` and then quits.

**Comment by AaronVanGeffen** [comment]
Thanks for the report. It's very unfortunate that this kind of bug made it into the release. Most of our devs are not on Windows, which is likely the reason this was overlooked.

Does the issue also present itself with a recent development build? I ask because #430 (#434) fixed a bug that might be related. You could try the artefact for [this job](https://github.com/OpenLoco/OpenLoco/suites/683449394/artifacts/6338079), for example.

Regardless, I intend to get this sorted for the next release.
