### ISSUE TITLE
Idle vehicle audio stacks and clips to painful volume levels when game speed is altered

### ISSUE THREAD

**Issue by Jeanfeels** [OpenLoco/OpenLoco#865]
**Version information:**
 - Platform: Windows 10
 - Version: 21.03-30
 - Build/commit: e6de736

**Describe the bug**
Vehicle idle sounds clip badly and stack while time warping, and can stack to painful volume levels when returning to regular speed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Center view over a busy station area with many trains kept in view (though this can occur rarely with just one or two trains present)
2. Use 2x and 3x time warp for a short while
3. Observe idle sounds clip in and out while stacking
4. While idle sound such as steam hiss is stacked, return to regular speed. This may take a couple of tries.
5. Observe that while the clipping in and out stops, the stacking of audio causes the idle sound to at least double in volume until the locomotive sound source has left the viewport or you pause and resume.

**Expected behaviour**
Audio should not stack to painful levels; audio should not clip in and out spasmatically.

**Screenshots**
Video: https://youtu.be/s8qwZOVGF14

**Additional context**
May be related to #239

**Comment by LeftofZen** [comment]
Some info from my testing today:
- I set a breakpoint hoping to catch the loud audio bug but it doesn't seem to occur on a debug build, probably because the fps is very low in debug builds, which means you can't fast-forward the game to trigger it very easily.
- I tested on vanilla Locomotion and I didn't experience the loud sounds, on any of the audio device settings.
- The bug seems to occur only with steam engine trains as I wasn't able to get it to happen with any kind of electric train.

**Comment by AaronVanGeffen** [comment]
I believe this has been resolved. @Jeanfeels, could you confirm?

**Comment by LeftofZen** [comment]
I also believe this has been resolved now with the openal rewrite

**Comment by duncanspumpkin** [comment]
Yes this was caused by the inability to change pitch which we now have.
